config/routes.rb
JobBoard::Application.routes.draw do
  root to: "jobs#premium"

  get "companies/login", to: "login#new"
  post "companies/login", to: "login#create"
  get "companies/logout", to: 'login#destroy'
  resources :companies, only: [:new, :create, :show]

  resources :jobs do
    post "comments", to: "comments#create"
  end
  delete "comments/:id", to: "comments#destroy", as: :comment
  get "hello/world"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :job, counter_cache: true
  attr_accessible :body, :job_id, :name
  validates_presence_of :body, :job_id, :name
end

app/models/company.rb
require "bcrypt"
class Company < ActiveRecord::Base
  has_many :jobs
	validates_presence_of :email, :name, :password
	validates_uniqueness_of :email
	validates_length_of :password, minimum: 6
	validates_confirmation_of :password
  attr_accessible :email, :name, :password, :password_confirmation

  def password=(new_password)
  	@password = new_password
  	self.encrypted_password = BCrypt::Password.create(@password)
  end

  def password
  	@password
  end

  def valid_password?(password_to_validate)
   BCrypt::Password.new(encrypted_password) == password_to_validate
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :company
  has_many :comments
  scope :most_recent, order("created_at DESC")
  attr_accessible :description, :title, :premium
  validates_presence_of :description, :title, :company_id
  def to_param
    "#{id}-#{title}"
  end
  
  def self.find_by_slug(slug)
    result = find(slug)
    if result.to_param == slug
      result
    else
      raise SlugError.new(result)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale
  
  rescue_from SlugError, :with => :rescue_from_slug_error

  private
  def current_company
  	@current_company ||= if session[:company_id]
  		@company_id = Company.find_by_id(session[:company_id])
  	end
  end
  helper_method :current_company
  
  def set_locale
    locale = params[:locale] || cookies[:locale]
    
    if locale.present?
        I18n.locale = locale
        cookies[:locale] = {value: locale, expire: 30.days.from_now}
    end
  end

  def rescue_from_slug_error(exeption)
    redirect_to exeption.objeto
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @job = Job.find(params[:job_id])
    @comment = @job.comments.build(params[:comment])
    
    if success = @comment.save
        NewComment.new_comment(@job, @comment).deliver
    end
    respond_to do |format|
        format.html do
            if success
              flash[:notice] = "Comment was created with success!"
            else
              flash[:alert] = "Please fill in all fields to create a comment."
            end
            redirect_to @job
        end
        format.js 
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @comment.job, notice: "Comment destroyed with success."
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	def new
		@company = Company.new
	end
  
	def create
		@company = Company.new(params[:company])

		if @company.save
			redirect_to root_path, notice: "The company has been created."
		else
			render action "new"
		end
	end
  
  def show
    @company = Company.find(params[:id])
    render json: @company, except: [:encripted_password], include: [:jobs]
  end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def world
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authorize_company, only: [:new, :create, :edit, :update, :destroy]
  # GET /jobs
  # GET /jobs.json
  def index
    @id_minimo = params[:id_minimo]
    if @id_minimo
      lista_parcial = Job.where("id > ?", @id_minimo)
    else
      lista_parcial = Job
    end
    @job = lista_parcial.most_recent.includes(:company).all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
      format.atom {
        if Job.first
          @last_updated = Job.first.updated_at
        else
          @last_updated = Time.now
        end
        }
    end
  end

  def premium
    @jobs = Job.where(premium: true).includes(:company).most_recent.
      paginate(page: params[:page], per_page: 10)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find_by_slug(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = current_company.jobs.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = current_company.jobs.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = current_company.jobs.build(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = current_company.jobs.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = current_company.jobs.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  private

  def authorize_company
    unless current_company
      redirect_to root_path, alert: "You need stay logged to acess this page"
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
	def new
	end

	def create
		company = Company.find_by_email(params[:company][:email])

	    if company && company.valid_password?(params[:company][:password])
	      session[:company_id] = company.id
	      redirect_to root_path
	    else
	      flash.now[:alert] = "Invalid e-mail or password."
	      render action: "new"
	    end
	end
	def destroy
		session.clear
		redirect_to root_path	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def job_title(job)
    title = raw("#{h(job.title)} - #{h(job.company.name)}")

    if job.premium
      title + content_tag(:strong, " (premium)")
    else
      title
    end
  end
end

app/views/comments/_comment.html.erb
    <h4><%= t ".said", name: comment.name %></h4>
    <%= simple_format comment.body %>
    Sent <%= t ".send", timestamp: time_ago_in_words(comment.created_at) %> ago
    <%= link_to t('link.destroy'), comment_path(comment), method: :delete, confirm: t('link.destroy_confirmation')  %>

app/views/comments/_form.html.erb
<%= form_for [@job, Comment.new], html: { class: 'form-horizontal' }, remote: true do |f| %>
  <div class="control-group">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :body, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, rows: 5 %>
    </div>
  </div>
  <div class="control-group controls">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/comments/create.js.erb
<% if @comment.errors.empty? %>
    $('#comments').append('<%=j render(@comment) %>');
    $('#new_comment')[0].reset();
    $('.alert-success').text('The comments has been created!');
<% else %>
    $('.alert-erro').text('Erro: fill all the fields!');
<% end %>

app/views/companies/_form.html.erb
<%= form_for(@company, html: {class: 'form-horizontal' }) do |f| %>
	<% if @company.errors.any? %>
		<div class="alert alert-error">
			<h3><%= pluralize(@company.errors.count, "error")%> prohibited this company from being saved:</h3>
			<ul>
				<% company.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
<% end %>

<div class="control-group">
	<%= f.label :name, class: "control-label" %>
	<div class="controls">
		<%= f.text_field :name %>
	</div>
</div>

<div class="control-group">
	<%= f.label :email, class: 'control-label' %>
	<div class="controls">
		<%= f.text_field :email %>
	</div>
</div>

<div class="control-group">
	<%= f.label :password, class: 'control-label' %>
	<div class="controls">
		<%= f.password_field :password %>
	</div>
</div>

<div class="control-group">
	<%= f.label :password_confirmation, class: 'control-label' %>
	<div class="controls">
		<%= f.password_field :password_confirmation %>
	</div>
</div>

<div class="control-group controls">
	<%= f.submit class: 'btn btn-primary' %>
</div>
<% end %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %> | 
<%= link_to 'Login', companies_login_path %> 

app/views/hello/world.html.erb
<h1>Hello World</h1>
<strong><%= Time.now %></strong>

app/views/jobs/_form.html.erb
<%= form_for(@job, html: { class: 'form-horizontal' }) do |f| %>
  <% if @job.errors.any? %>
    <div class="alert alert-error">
      <h3><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h3>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.label :premium, class: 'checkbox' do %>
        <%= f.check_box :premium, rows: 10 %> Premium
      <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, rows: 10 %>
    </div>
  </div>
  <div class="control-group controls">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<h3><%= job_title job %></h3>

<%= simple_format job.description %>

<p>
  <%= pluralize(job.comments.size, "comment") %> |
  <%= link_to 'Show', job %>
  <% if current_company == job.company %>
  	|<%= link_to 'Edit', edit_job_path(job) %> 
  	|<%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</p>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<%= auto_discovery_link_tag :atom, jobs_url %>
<h1><%= t ".listing" %></h1>

<%= render @jobs %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/premium.html.erb
<h1>Premium jobs</h1>

<%= render @jobs %>
<%= will_paginate @jobs %>

app/views/jobs/show.html.erb
<h1><%= job_title @job %></h1>

<%= simple_format @job.description %>

<p>
  <%= pluralize(@job.comments.size, t("comments.count")) %> |
  <% if current_company == @job.company %>
  	<%= link_to t('link.edit'), edit_job_path(@job) %> |
  <% end %>
  <%= link_to t('link.back'), jobs_path %>
</p>

<h2><%= t ".new_comment" %></h2>
    <%= render "comments/form" %>
<h2><%= t ".comments" %></h2>
<div id="comments">
    <%= render @job.comments %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>JobBoard</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="/" title="Job Board">Job Board</a>
        
        <ul class="nav">
            <% if locale == 'en'%>
                <li><%= link_to 'Português', locale: 'pt-br'%></li>
            <% else %>
                <li><%= link_to 'English', locale: 'en'%></li>
            <% end %>
        </ul>

        <ul id="app-menu" class="nav pull-right">
          <li><%= link_to t("menu.premiun_jobs"), root_path %></li>
          <li><%= link_to t("menu.all_jobs"), jobs_path %></li>

          <% if current_company %>
            <li><%= link_to t("menu.new_job"), new_job_path %></li>
            <li><a>Logged as <%= current_company.name %></a></li>
            <li><%= link_to t("menu.logout"), companies_logout_path%></a></li>
          <% else %>
            <li><%= link_to t("menu.new"), new_company_path %></li>
            <li><%= link_to t("menu.login"), companies_login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <% if notice %><p class="alert alert-success"><%= notice %></p><% end %>
    <% if alert %><p class="alert alert-error"><%= alert %></p><% end %>

    <%= yield %>
  </div>

  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/login/_form.html.erb
<%= form_for(Company.new, url: companies_login_path, html: { class: 'form-horizontal' }) do |f| %>

	<div class="control-group">
		<%= f.label :email, class: 'control-label' %>
		<div class="controlls">
			<%= f.text_field :email %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :password, class: 'control-label' %>
		<div class="controlls">
			<%= f.password_field :password %>
		</div>
	</div>

	<div class="control-group">
		<%= f.submit 'Login', class: 'btn btn-primary' %>
	</div>

<% end %>

app/views/login/new.html.erb
<h1>Company login</h1>
<%= render "form" %>
<%= link_to "Back", root_path %> |
<%= link_to 'Create a new account.', new_company_path %>

app/views/new_comment/new_comment.html.erb
Hello <%= @company.name %>

You have a new coment about <%= @job.title %> job:
name: <%= @comment.name %>
body: <%= @comment.body %>

You can see all comment of this job here: <%= job_url(@job) %>

app/views/new_comment/new_comment.pt-BR.html.erb
<p>Olá <%= @company.name %></p>

<p>Você tem um novo comentario sobre a vaga <%= @job.title %>:</p>
<p>
    <em>Nome: <%= @comment.name %></em>
    <em>Mensagem: <%= @comment.body %></em>
</p>

<p>Você pode ver todos os commentarios sobre essa vaga <%= link_to 'aqui.', job_url(@job) %></p>

app/views/new_comment/new_comment.text.erb
Hello <%= @company.name %>

You have a new coment about <%= @job.title %> job:
name: <%= @comment.name %>
body: <%= @comment.body %>

You can see all comment of this job here: <%= job_url(@job) %>